In [1]:
#write a python code to check to check th version of numpy
import numpy as np
print(np.__version__)

2.1.0


In [5]:
#WRITE PYTHON PROGRAM TO TEST IF ANY OF ELEMENT OF A GIVEN ARRAY ARE NON ZERO
import numpy as np
x=np.array([1,0,0,0])
print(np.array(x))
print(np.any(x))

x=np.array([0,0,0,0])
print(np.array(x))
print(np.any(x))

[1 0 0 0]
True
[0 0 0 0]
False


In [7]:
#write python program to test a given array element wise for finiteness (not infinite or not number)
import numpy as np
x=np.array ([1,0,np.nan,np.inf])    #nan is not a number
print(x)                            #inf is infinite
print("test a give element wse for finitness:")
print(np.isfinite(x))


[ 1.  0. nan inf]
test a give element wse for finitness:
[ True  True False False]


In [10]:
#write a python program to test element wise positive or negative infinity
import numpy as mnp
x=mnp.array([1,0,-2,mnp.inf,-mnp.inf,3.4,6,7])
result_pos_inf=mnp.isposinf(x)
result_neg_inf=np.isneginf(x)
print(result_pos_inf)
print(result_neg_inf)

[False False False  True False False False False]
[False False False False  True False False False]


In [13]:
# write a python to create an array of integers from 30 to 70
import numpy as pd
x=pd.arange(30,71)
print(x)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [15]:
#WRITE A PYTHON PROGRAM TO CREATE ARRAY OF ALL EVEN INTEGER FROM 30 TO 70
import numpy as pd
x= pd.arange(30,71,2)
print(x)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [16]:
# wirte a python code to create 3x3 identity 
import numpy as pd
arr_2d=pd.identity(3)
print(arr_2d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#write a python to create a 5x5 zero matrix with element on the main diagonal equal to 1,2,3,4,5
import numpy as pd
arr_2d=pd.diag([1,2,3,4,5,7,8,4,5,6,9,34,5,6,7,8])
print(arr_2d)

[[ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  4  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  9  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 34  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  5  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  6  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  7  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  8]]


In [29]:
#write a python to generate matrix product of 2 arrays
import numpy as np
x=[[1,0],[1,1]]
y=[[3,1],[2,2]]
print(np.dot(x,y))
#or
print(np.matmul(x,y))


[[3 1]
 [5 3]]
[[3 1]
 [5 3]]


In [61]:
#Write a python program to generate  of matrix addition of 2 array 
import numpy as np
arr1=np.array([10,11,12,13,15,16,17])
arr2=np.array([23,24,252,62,267,5,7])
print("matrix addition")
newadd=np.add(arr1,arr2)
print(newadd)
print('matrix subtraction')
newsub=np.subtract(arr1,arr2)
print(newsub)

matrix addition
[ 33  35 264  75 282  21  24]
matrix subtraction
[ -13  -13 -240  -49 -252   11   10]


In [45]:
#write to find mean of 1d array
import numpy as np
arr1=np.array([(10+20+30+40+50)])
me=np.mean(arr1)
print(me)


30.0


In [59]:
#find mean of row
import numpy as np
x=np.array ([[10,30],[20,60]])
print('original array')
print(x)
print('mean of each column')
print(x.mean(axis=0))
print('mean of each row')
print(x.mean(axis=1))

original array
[[10 30]
 [20 60]]
mean of each column
[15. 45.]
mean of each row
[20. 40.]


In [60]:
#to create 1D array in range 0 to9
import numpy as pd
x= pd.arange(0,10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [68]:
# to convert 1d to 2d with 2 rows
arr1=np.array([1,2,3,4,5,6,7,8])
y=x.reshape(2,4)
print(arr1)
print(y)

ValueError: cannot reshape array of size 10 into shape (2,4)